### PR TITLE
* My question was what the importance of the makefile is

### PR DESCRIPTION
**Pull request by icecreammatt**

### CODE REVIEW

**Comment by icecreammatt** [comment]
@dee-mo It looks like you missed this question. I'll use it as a demo on Thursday on how to update your fork of the code base with the latest so it can be merged in.

**Comment by dee-mo** [comment]
Oh jeez, sorry.
Looking forward to the demo Thursday then!

**Comment by icecreammatt** [comment]
No worries!

**Comment by icecreammatt** [comment]
I've manually merged this into the master branch.

**Pull request closed without merging**
